### ISSUE TITLE
大佬能不能做一个OC引导

### ISSUE THREAD

**Issue by eatmybigJB** [louislivi/Hackintosh#1]
首先十分感谢你分享的EFI，之前是上淘宝找别人帮忙装的，换了几个技术都没装上，一直卡在读条上，最后说搞不定退款，正在绝望之际，找到了你这个仓库，粗略看了下一些教程决定自己试一下，自己第一次动手装黑苹果并用了你的EFI就成功了，十分激动，我的配置和你有点出入但基本上算是完美运行(Z390-E+8700k+5700xt+RD500 1T)，目前除了有一个USB口插了没反应之外，其他都正常，icloud和app store都能用，本人纯小白，对那些什么引导层面的东西完全不懂，完全使用你的EFI到现在没有修改过任何参数，感觉挺好，我看了很多论坛说OC引导的5700xt比clover要好些，期待你能分享一个OC的EFI，谢谢大佬

**Comment by louislivi** [comment]
#18a2629f8efa5a2a1365e1401a27e852608e3132

> 引导已更新。
